version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    ports:
      - ${PORT_DB}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - pgdata:/data/db
      #- ./create.sql:/docker-entrypoint-initdb.d/create_tables.sql
  auth:
    image: node:20
    command: bash -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    depends_on:
      - 'db'
    working_dir: /app
    volumes:
      - ./auth/:/app
    ports:
      - ${PORT_AUTH_SERVICE}:${PORT_AUTH_SERVICE}
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_URL: 'http://${HOST}:${PORT_M1_SERVICE}'
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public

volumes:
  pgdata:
  app:
