version: '3.9'
services:
  db:
    image: postgres:16.1-alpine
    ports:
      - ${PORT_DB}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      #- ./create.sql:/docker-entrypoint-initdb.d/create_tables.sql
  auth:
    image: node:20
    command: bash -c "npm install && npm run watch"
    depends_on:
      - 'db'
    working_dir: /app
    volumes:
      - ./auth/:/app
    ports:
      - ${PORT_AUTH_SERVICE}:8010
      - ${EMAIL_PORT}:${EMAIL_PORT}
    environment:
      PORT_AUTH_SERVICE: ${PORT_AUTH_SERVICE}
      NODE_ENV: ${NODE_ENV}
      APP_URL: 'http://${HOST}:${PORT_AUTH_SERVICE}'
      FRONT_URL: 'http://localhost:${PORT_FRONT_APP}'
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public

      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}

      SMSC_HOST: ${SMSC_HOST}
      SMSC_USER: ${SMSC_USER}
      SMSC_PASS: ${SMSC_PASS}

      GOOGLE_AUTH_CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
      GOOGLE_AUTH_CLIENT_SECRET: ${GOOGLE_AUTH_CLIENT_SECRET}
      GOOGLE_AUTH_URI: ${GOOGLE_AUTH_URI}
      GOOGLE_AUTH_TOKEN: ${GOOGLE_AUTH_TOKEN}
      GOOGLE_AUTH_PROFILE_URI: ${GOOGLE_AUTH_PROFILE_URI}

      YANDEX_AUTH_CLIENT_ID: ${YANDEX_AUTH_CLIENT_ID}
      YANDEX_AUTH_CLIENT_SECRET: ${YANDEX_AUTH_CLIENT_SECRET}
      YANDEX_AUTH_PROFILE_URI: ${YANDEX_AUTH_PROFILE_URI}

  front:
    image: node:20
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./front:/app
     # - ./shared:/app/src/shared
    ports:
      - ${PORT_FRONT_APP}:3000
    environment:
      SECRET_JWT: ${SECRET_JWT}
      APP_URL: 'http://${HOST}:${PORT_FRONT_APP}'
      BACK_URL: 'http://localhost:${PORT_AUTH_SERVICE}'